#!/bin/bash
OLD=`pwd`
ROOT=`dirname $0`
cd $ROOT
ROOT=`pwd`
BASE="${ROOT}/projects/"
PROJECTS=`ls ${BASE}`
md5=`echo $PROJECTS | md5sum`
if [ -f "projects.md5" ]; then
    old_md5=`cat projects.md5`
fi
echo "$md5" > projects.md5
reload=0
restart=0
if [ "$md5" != "$old_md5" ]; then
    echo "new projects found, reloading, '$md5' '$old_md5'"
    restart=1
fi

for P in $PROJECTS; do
    echo $P
    cd "${BASE}${P}"
    gp=`git pull -q`
    echo $gp | grep 'lib/'
    if [ "$?" != "0" ]; then
        echo "  No updates"
    else
        echo "  lib updated"
        reload=1
    fi
    if [ "$reload" == 1 ]; then
        cpanm --installdeps .
        make distclean
    fi
done
cd $ROOT
pwd
./status
status=$?
if [ "$status" == "1" ]; then
    # the pid file exists, but no running process, crashed
    echo "removing pid-file, then restarting"
    rm server.pid
    ./starter
elif [ "$status" == "2" ]; then
    # No pid file, starting
    echo "no running server, starting"
    ./starter
else
    if [ "$restart" == "1" ]; then
        echo "stopping and starting, new projects"
        ./stopper
        ./starter
    elif [ "$reload" == "1" ]; then
        echo "reloading.."
        ./reloader
    fi
fi
cd $OLD
