#!/bin/sh
ROOT=`dirname $0`
cd $ROOT
ROOT=`pwd`
echo "ROOT: $ROOT"
BASE="${ROOT}/projects/"
PROJECTS=`ls ${BASE}`
md5=`echo $PROJECTS | md5sum`
old_md5=`cat projects.md5`
echo "new md5: $md5  old: $md5"
echo $md5 > projects.md5
OLD=`pwd`
reload=0
if [ "$md5" != "$old_md5" ]; then
    reload=1
fi

for P in $PROJECTS; do
    echo $P
    cd "${BASE}${P}"
    gp=`git pull -q`
    echo $gp | grep -q 'lib/'
    if [ "$?" != "0" ]; then
        echo "No updates, not reloading"
    else
        echo "Match, restart"
        reload=1
    fi
done
cd $ROOT
./status

if [ "$?" == "1" ]; then
    # the pid file exists, but no running process, crashed
    echo "removing pid-file, then restarting"
    rm server.pid
    ./starter
elif [ "$?" == "2" ]; then
    # No pid file, starting
    echo "no running server, starting"
    ./starter
else
    if [ $reload == 1 ]; then
        echo "reloading.."
        ./reloader
    fi
fi
cd $OLD
